services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orders-php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8080"

      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-orders}
      DB_USERNAME: ${DB_USERNAME:-orders}
      DB_PASSWORD: ${DB_PASSWORD:-orders}
      SESSION_DRIVER: file
      LOG_CHANNEL: ${LOG_CHANNEL:-stderr_json}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - orders_net

  nginx:
    image: nginx:1.27-alpine
    container_name: orders-nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./src:/var/www/html:ro # ro = read only
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # ro = read only
    depends_on:
      - php
    networks:
      - orders_net

  db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orders}
      POSTGRES_USER: ${POSTGRES_USER:-orders}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orders}
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orders} -d ${POSTGRES_DB:-orders}"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432" # map container port to host port for debugging purposes
    networks:
      - orders_net

networks:
  orders_net:

volumes:
  orders_db_data:
